volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
        ports:
            - "6379:6379"
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        image: "travel-agent"
        ports:
            - "8124:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            OPENAI_API_KEY: "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"
            LANGSMITH_API_KEY: "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"
            WEATHERAPI_KEY: "3cf406570f684e5ca9f101822252603"
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable